onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - '@tree-sitter-grammars/tree-sitter-yaml'
  - core-js-pure
  - prisma
  - sharp
  - tree-sitter
  - tree-sitter-json
  - unrs-resolver
